// Generated by CoffeeScript 1.6.1
(function() {

  describe('initializing the app', function() {
    beforeEach(function() {
      return setTestMode();
    });
    return it('sends me to tables.index', function() {
      currentPath;      Ember.run(function() {
        var currentPath;
        return currentPath = App.__container__.lookup('controller:application').get('currentPath');
      });
      return expect(currentPath).to.equal('tables.index');
    });
  });

}).call(this);
